const Discord = require('discord.js');
let answers = [ 
    "\n ``` ```\n **__Clan Aburame (油女一族)__**\n \`\`\`diff\n- Le Clan Aburame (油女一族, Aburame Ichizoku) est un clan caractérisé par leur utilisation des insectes comme armes. Les insectes vivent en symbiose dans le corps du shinobi. À la naissance, les membres de ce clan sont offerts à une race particulière d'insectes appelés Kikaichû, le corps leur servant de nid. Les insectes peuvent entrer et sortir au moyen de diverses pores, apparemment en mangeant leur chemin à travers la peau. Ils se nourrissent de chakra comme une source de nourriture, les rendant tout à fait mortel. La relation entre le shinobi et les insectes est mutuellement bénéfique. Les insectes permettent de faire des techniques.\`\`\`\n ``` ``` \n https://thumbs.gfycat.com/FloweryArtisticBongo-size_restricted.gif",
    "\n ``` ```\n **__Clan Akimichi (秋道一族)__**\n \`\`\`diff\n- Le Clan Akimichi (秋道一族, Akimichi Ichizoku) est un clan de Konoha. Ses membres sont capables de convertir rapidement les calories en chakra, qu'ils utilisent ensuite pour leurs techniques secrètes, telles le Décuplement et les autres variantes de jutsu d'agrandissement du corps. La plupart de ces techniques sont connues pour épuiser rapidement les réserves de chakra de l'utilisateur, le fatiguant très vite durant un combat. C'est la raison pour laquelle les Akimichi ont tendance à beaucoup manger, même avant un combat, afin de régénérer constamment leur réserve de chakra. C'est pourquoi le symbole du clan, inscrit sur la plupart des tenues des membres, est le kanji stylisé du mot « nourriture ». Si les techniques habituelles ne sont pas suffisantes durant un combat, un Akimichi peut faire usage des trois pilules de couleur pour convertir la graisse excessive en chakra, mais à ses risques et périls : les pilules, en particulier la dernière, la rouge, sont extrêmement dangereuses pour le corps humain et leur consommation peut aboutir à la mort.\`\`\`\n ``` ``` \n https://media0.giphy.com/media/IQsSHDNz1o05q/giphy.gif",
    "\n ``` ```\n **__Clan Hatake (はたけ一族)__**\n \`\`\`diff\n- Le Clan Hatake (はたけ一族, Hatake Ichizoku) est l'un des nombreux clans résidant au village caché de Konoha.\`\`\`\n ``` ``` \n https://media0.giphy.com/media/1AN73nSrDYhiM/giphy.gif",
    "\n ``` ```\n **__Clan Hyûga (日向一族)__**\n \`\`\`diff\n- Le Clan Hyûga (日向一族, Hyûga Ichizoku) est l'un des plus anciens et le plus puissant des clans de Konoha. D'après Neji, son clan possède les plus puissantes techniques qui existent. Tous les membres de la famille naissent avec le Byakugan, un Kekkei Genkai leur donnant un champ de vision de 360°, la possibilité de distinguer le système circulatoire du chakra et les cavités de chakra (Tenketsu), de voir sur des kilomètres de distance et à travers les êtres et les objets.\`\`\`\n ``` ``` \n https://media1.tenor.com/images/528280c39e2efcfdff1ffc871fcb496b/tenor.gif?itemid=11582747",
    "\n ``` ```\n **__Clan Inuzuka (犬塚一族)__**\n \`\`\`diff\n- Le Clan Inuzuka (犬塚一族, Inuzuka Ichizoku) est connu pour son affinité avec les chiens ninjas, avec qui les membres du clan combattent. Un membre du clan Inuzuka se voit attribuer un (ou des) partenaire(s) canin(s) lorsqu'il atteint un certain âge. Étant donné leur affinité naturelle avec les chiens, un Inuzuka et son partenaire animal s'attachent très vite jusqu'à devenir inséparables. Les membres du clan possèdent des marques rouges en forme de crocs sur les joues, ainsi que des yeux et des canines pointues faisant ressortir leur animalité. Les liens très forts entre un Inuzuka et son partenaire canin sont si forts qu'ils permettent de combiner et partager leur chakra, permettant à l'humain de prendre une apparence plus sauvage et à l'animal de prendre une apparence plus humaine. Cette combinaison leur permet d'exécuter des techniques en collaboration telles que les Crocs Lacérants.\`\`\`\n ``` ``` \n https://thumbs.gfycat.com/RadiantNauticalBarasinga-size_restricted.gif",
    "\n ``` ```\n **__Clan Kurama (鞍馬一族)__**\n \`\`\`diff\n- Le Clan Kurama (鞍馬一族, Kurama Ichizoku), seulement apparu dans l'anime, est un clan excellant dans les techniques de genjutsu. Ce talent inné dans le genjutsu est dû à un kekkei genkai que le clan possède. Cependant, une fois toutes les quelques générations, un membre du clan né avec un tel potentiel dans le genjutsu que ses illusions peuvent réellement produire des effets qui surviennent dans la réalité. Le genjutsu est tellement puissant qu'il oblige le cerveau à faire dans la réalité tout ce qui arrive à la victime dans l'illusion, permettant aux membres du clan de potentiellement tuer leurs opposants avec le genjutsu. \`\`\`\n ``` ``` \n https://vignette.wikia.nocookie.net/naruto/images/5/5b/Murakumo_Kurama.JPG/revision/latest?cb=20120725174620&path-prefix=fr",
    "\n ``` ```\n **__Clan Lee (リー一族)__**\n \`\`\`diff\n- Le clan Lee (リー一族, Rī Ichizoku) est un clan qui réside dans le village de Konoha. Le clan semble spécialisé dans le domaine du taijutsu.\`\`\`\n ``` ``` \n https://media1.giphy.com/media/4ExWdLKTCaz16/giphy.gif",
	"\n ``` ```\n **__ Clan Nara (奈良一族)__**\n \`\`\`diff\n- Le Clan Nara (奈良一族, Nara Ichizoku) est connu pour la maîtrise de ses membres de la Manipulation des Ombres et l'affection particulière qu'il porte aux cerfs, lesquels vivent dans une zone étendue, la forêt du clan Nara. Depuis des générations, ce clan garde un livre sur des préparations médicinales ce qui laisse entendre que le clan ait un rapport avec la médecine. Parmi les secrets contenus dans ce livre, on trouve les pilules utilisées par le clan Akimichi.\`\`\`\n ``` ``` \n https://lh3.googleusercontent.com/proxy/Aqf4WAvHr4RGnBDBm1cRxa3qm_BUNb7UOkiVKWCYeVkW7YzuNKQ9O7cnB7tWEXOZSvCBkBfUkRUx_iRlFN8nrqXXvJGOdYGHASNcMLpUTUU",
	"\n ``` ```\n **__Clan Sarutobi (猿飛一族)__**\n \`\`\`diff\n- Le Clan Sarutobi (猿飛一族, Sarutobi Ichizoku) est un clan d'une grande influence de Konoha. our renforcer l'unité entre les clans Akimichi, Nara et Yamanaka, il devint une tradition qu'un membre de ce clan devienne le maître des formations Ino-Shika-Chô se succédant à travers les générations, et qu'il leur offre des boucles d'oreilles quand ils prêtaient serment.\`\`\`\n ``` ``` \n https://media1.tenor.com/images/88bc924bdea688da51b75a4788451f6e/tenor.gif?itemid=5247363",
	"\n ``` ```\n **__Clan Senju (千手一族)___**\n \`\`\`diff\n- Le clan Senju (千手一族, Senju Ichizoku) était l'un des clans les plus puissants de l'époque, qui avait pour chef, le redoutable et unique utilisateur naturel du Mokuton, Hashirama Senju, qui devint plus tard, le premier Hokage. Ils avaient pour rivaux, le clan Uchiwa dont leur chef, Madara Uchiwa, fut le plus grand et unique rival d'Hashirama Senju. Ils furent à l'origine de la création du village caché des feuilles avec le clan Uchiwa. Il fut également révélé qu'ils auraient des liens de parenté éloignés avec le clan Uzumaki.\`\`\`\n ``` ``` \n https://media3.giphy.com/media/Te4NwB59ZFn68/giphy.gif",
	"\n ``` ```\n **__Clan Shimura (志村一族)__**\n \`\`\`diff\n- Le Clan Shimura (志村一族, Shimura Ichizoku) est un clan de ninjas de Konoha. Après la fondation du village de Konoha succédant à l'Époque Sengoku, les Shimura furent parmi les premiers clans à s'allier avec les clans Senju et Uchiwa ayant fondé le village, en même temps que le clan Sarutobi.\`\`\`\n ``` ``` \n https://media.giphy.com/media/CIOLMneW879As/giphy.gif",
	"\n ``` ```\n **__Clan Uzumaki (うずまき一族)__**\n \`\`\`diff\n- Le Clan Uzumaki (うずまき一族, Uzumaki Ichizoku) était le clan prédominant du Village caché des Remous. Ce clan avait un lointain lien de parenté avec le clan Senju avec lequel ils ont toujours entretenu de bonnes relations. Ils furent décimés lors des Grandes Guerres Ninjas en même temps que le Pays des Tourbillons. Les rares survivants s'exilèrent à travers le monde. Depuis, les ninjas du village de Konoha arborent le symbole Uzumaki sur leurs uniformes, en mémoire de leurs amis défunts.\`\`\`\n ``` ``` \n https://i.pinimg.com/originals/06/a4/72/06a472766b5c90c0959a572eaaa6fb4b.gif",
	"\n ``` ```\n **__Clan Uchiwa (うちは一族__**\n \`\`\`diff\n- Le clan Uchiwa (うちは一族, Uchiha Ichizoku) était autrefois considéré comme le plus puissant clan de Konoha et un des plus puissants du monde ninja (avec pour seul et unique rival le clan Senju avec lequel il fonda Konoha).\`\`\`\n ``` ``` \n https://media1.giphy.com/media/8qXJTU5oEhQZO/giphy.gif",
	"\n ``` ```\n **__Clan Yamanaka (山中一族)__**\n \`\`\`diff\n- Le Clan Yamanaka (山中一族, Yamanaka Ichizoku) est une famille de ninjas de Konoha. Ils possèdent et dirigent un magasin de fleurs dans le village de Konoha. Les membres de ce clan se spécialisent dans les techniques centrés sur l'esprit ce qui les rend experts dans la collecte de renseignements et d'espionnage. Ils ont également affiché des aptitudes sensorielles et leurs techniques incluent le transfert de la conscience, lire dans les pensées et de communiquer par télépathie.\`\`\`\n ``` ``` \n https://thumbs.gfycat.com/AntiqueImpoliteArmyworm-small.gif",

]


module.exports.run = (client, message, args) => {

    const answer = answers[Math.floor(Math.random() * answers.length)];

        message.reply(answer)
};

module.exports.help = {
    name: 'nrp!clan-konoha'
};
